#!/bin/bash

# Small bash script to download the required models for both Spleeter and Demucs and put them in the right place
# This prevents having to download these models on first run, useful when running the repository remotely e.g. on Binder
echo "Downloading pretrained models for Spleeter and Demucs..."

### SPLEETER DOWNLOAD
# Set the URL of the .tar.gz file to download
file_url="https://github.com/deezer/spleeter/releases/download/v1.4.0/5stems.tar.gz"

# Set the name of the new directory to extract the contents
extracted_dir="pretrained_models/5stems"

# Create the new directory if it doesn't exist
mkdir -p "$extracted_dir"

# Download the .tar.gz file
wget "$file_url" -O /tmp/downloaded_file.tar.gz

# Check if the download was successful
if [ $? -eq 0 ]; then
    # Extract the contents to the new directory
    tar -xzf /tmp/downloaded_file.tar.gz -C "$extracted_dir"
    # Clean up the downloaded .tar.gz file
    rm /tmp/downloaded_file.tar.gz
    echo "Extraction completed successfully. Files are in: $extracted_dir"
else
    echo "Download failed. Please check the URL and try again."
fi

# Copy the Spleeter model to the src directory in case we're running from there
mkdir -p src/clean/pretrained_models
cp -r pretrained_models/5stems src/clean/pretrained_models

### DEMUCS DOWNLOAD
# Torch provides helper commands to do this all for us...
python3 -c "import torch; torch.hub.load_state_dict_from_url('https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/5c90dfd2-34c22ccb.th', map_location='cpu', check_hash=True)"

### MVSEP DOWNLOAD
# Clone the repository
git clone https://github.com/ZFTurbo/MVSEP-MDX23-music-separation-model

# In Python, run the commands in torch to download the models to the required directory
python3 -c "import torch; torch.hub.download_url_to_file('https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/04573f0d-f3cf25b2.th', 'MVSEP-MDX23-music-separation-model/models/04573f0d-f3cf25b2.th')"
python3 -c "import torch; torch.hub.download_url_to_file('https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/Kim_Inst.onnx', 'MVSEP-MDX23-music-separation-model/models/Kim_Inst.onnx')"
python3 -c "import torch; torch.hub.download_url_to_file('https://github.com/TRvlvr/model_repo/releases/download/all_public_uvr_models/Kim_Vocal_2.onnx', 'MVSEP-MDX23-music-separation-model/models/Kim_Vocal_2.onnx')"

echo "... Finished downloading pretrained models !"